"""Export a case wiki as a clean Obsidian-compatible vault.

The export is a flat copy of ``wiki/cases/<case_id>/`` minus the ``.fw/``
sidecar, plus:

  - ``graph.mmd``                  if the relationship graph exists
  - ``README_FOR_OBSIDIAN.md``     a short orientation page

We deliberately do **not** copy the ``.fw/`` sidecar. Vault users should
read markdown, not internal JSON.

The export destination defaults to ``examples/obsidian_vault_<case_id>/``
so reviewers can browse it without running the project.
"""
from __future__ import annotations

import shutil
from pathlib import Path

from .wiki_io import REQUIRED_PAGES, case_dir


def export_vault_dir(project_root: Path, case_id: str) -> Path:
    return project_root / "examples" / f"obsidian_vault_{case_id}"


def export_vault(
    project_root: Path,
    case_id: str,
    *,
    target: Path | None = None,
    overwrite: bool = True,
) -> Path:
    """Export the case wiki to a clean Obsidian-friendly vault folder."""
    src = case_dir(project_root, case_id)
    if not src.exists():
        raise FileNotFoundError(f"Case wiki not found at {src}")

    dst = target or export_vault_dir(project_root, case_id)
    if dst.exists():
        if not overwrite:
            raise FileExistsError(f"Vault already exists at {dst}; pass overwrite=True.")
        shutil.rmtree(dst)
    dst.mkdir(parents=True)

    # Copy every required markdown page.
    written: list[str] = []
    for name in REQUIRED_PAGES:
        sp = src / name
        if sp.exists():
            shutil.copy(sp, dst / name)
            written.append(name)

    # Copy graph.mmd if it exists (Phase 5 artifact).
    graph_mmd = src / ".fw" / "graph.mmd"
    if graph_mmd.exists():
        shutil.copy(graph_mmd, dst / "graph.mmd")
        written.append("graph.mmd")

    # Always ship a vault README.
    (dst / "README_FOR_OBSIDIAN.md").write_text(_render_vault_readme(case_id, written))
    written.append("README_FOR_OBSIDIAN.md")
    return dst


def _render_vault_readme(case_id: str, written: list[str]) -> str:
    return f"""# Obsidian Vault — `{case_id}`

This folder is an export of the compiled investigation wiki for
`{case_id}`. It is plain markdown — open this folder as an Obsidian
vault and the graph view will render the wiki-link relationships
between pages.

## Files

{chr(10).join(f"- `{p}`" for p in written)}

## How to use this vault

1. Open Obsidian and choose "Open folder as vault" → point at this directory.
2. The graph view shows every page and how `[[wiki link]]` references
   connect them.
3. `index.md` is the entry point. From there, follow `[[timeline]]`,
   `[[entities]]`, `[[iocs]]`, `[[hypotheses]]`, `[[contradictions]]`,
   `[[open_questions]]`, `[[final_report]]`.
4. `graph.mmd` (if present) is the GraphRAG-lite relationship diagram.
   GitHub and many Obsidian Mermaid plugins render it natively.

## What you should NOT edit here

- `raw_sources/` lives elsewhere in the project. It is **immutable**.
  Do not edit raw evidence in Obsidian.
- The `.fw/` sidecar (state, indexes, traces) is not included in this
  export. Don't try to round-trip it from Obsidian.

## Reviewing AI-proposed changes

The project ships a human review queue. Any wiki update that contains
a risky phrase (e.g. "confirmed malware") is held back from being
applied until a human approves or rejects it. See `docs/human_review.md`
in the project repo.

This vault is generated by `python fw.py export-obsidian {case_id}`.
"""
